export const getAllProducts = () => {
  return [
    {
      id: "Drink-1-coffeLatte",
      slug: "drink-coffelatte",
      name: "Coffe Latte",
      category: `Drink's`,
      categorySlug: "drink",
      price: 50_000,
      stock: 30,
      imageUrl: "/assets/images/coffe latte.png",
      description: `Coffee Latte is a classic coffee beverage made from a rich blend of espresso and creamy milk, creating a smooth and balanced flavor.`,
    },
    {
      id: "Drink-1-cappucino",
      slug: "drink-cappucino",
      name: "Cappucino",
      category: `Drink's`,
      categorySlug: "drink",
      price: 45_000,
      stock: 12,
      imageUrl: `/assets/images/cappucino.png`,
      description: `Cappuccino is an iconic coffee beverage that offers the perfect harmony of espresso, steamed milk, and a thick layer of milk foam.`,
    },
    {
      id: "Drink-1-americano",
      slug: "drink-americano",
      name: "Americano",
      category: `Drink's`,
      categorySlug: "drink",
      price: 40_000,
      stock: 0,
      imageUrl: `/assets/images/americano.png`,
      description: `Americano is a simple yet elegant coffee beverage made by combining espresso with hot water.`,
    },
    {
      id: "Drink-1-Mochaccino",
      slug: "drink-mochaccino",
      name: "Mochaccino",
      category: `Drink's`,
      categorySlug: "drink",
      price: 35_000,
      stock: 30,
      imageUrl: `/assets/images/Mochaccino.png`,
      description: `Mochaccino is a delicious coffee-based drink that combines the rich flavors of espresso, steamed milk, and chocolate.`,
    },
    {
      id: "Cake-2-chesee-cake",
      slug: "cake-chesee",
      name: "Cheseecake",
      category: `Cake's`,
      categorySlug: "cake",
      price: 40_000,
      stock: 20,
      imageUrl: `/assets/images/CheseeCake.png`,
      description: `Cheesecake is a delightful dessert made of a rich, creamy cheese layer on a crisp biscuit base.`,
    },
    {
      id: "Cake-2-Rainbow-cake",
      slug: "cake-rainbow",
      name: "Rainbow Cake",
      category: `Cake's`,
      categorySlug: "cake",
      price: 36_000,
      stock: 4,
      imageUrl: `/assets/images/RainbowCake.png`,
      description: `Rainbow Cake is an enchanting cake with vibrant, colorful layers that reflect the beauty of a rainbow.`,
    },
    {
      id: "Cake-2-Strawberry-cake",
      slug: "cake-strawberry",
      name: "Strawberry Cake",
      category: `Cake's`,
      categorySlug: "cake",
      price: 40_000,
      stock: 0,
      imageUrl: `/assets/images/StrawberryCake.png`,
      description: `Strawberry Cake is a delightful treat that combines the natural sweetness of fresh strawberries with a light, fluffy cake. er.`,
    },
    {
      id: "Cake-2-Banana-cake",
      slug: "cake-banana",
      name: "banana Cake",
      category: `Cake's`,
      categorySlug: "cake",
      price: 40_000,
      stock: 35,
      imageUrl: `/assets/images/BananaCake.png`,
      description: `Banana cake is a moist, soft, and flavorful cake made primarily with ripe bananas. It has a light texture and a natural sweetness that comes from the bananas, making it a perfect dessert for banana lovers.`,
    },
  ];
};
